const AUTH_PREFIX = "users/v1/auth";
const ONBOARD = "users/v1/onboard";
const PROFILE ="users/v1/profile";
const MEDIA="medias/v1/files";
const FEATURE="features/v1";
export const VIEW_IMAGE="medias/v1/files/view/thumb/"
export const API_TYPE_CONST = {
  LOGIN: `${AUTH_PREFIX}/login`,
  LOGOUT: `${AUTH_PREFIX}/logout`,
  GENERATE_ACCESS_TOKEN: `${AUTH_PREFIX}/generate/access-token`,
  FORGOT_PASSWORD: `${ONBOARD}/forgot-password`,
  VERIFY_OTP: `${ONBOARD}/verify-otp`,
  RESEND_VERIFY_OTP: `${ONBOARD}/resend-verify-otp`,
  CREATE_NEW_PASSWORD: `${ONBOARD}/create-new-password`,
  GET_PROFILE: `${PROFILE}/me`,
  UPDATE_AVARTAR: `/users/v1/profile/me/avatar`,
  CHANGE_PASSWORD:`/users/v1/users/change-password`,
  UPLOAD_IMAGE:`${MEDIA}/upload`,
  LIST_SALE:`${FEATURE}/admin/sales`,
  CREATE_SALE:`${FEATURE}/admin/sales/add-sales`,
  LIST_STAFF: `${FEATURE}/admin/staff`,
  ADD_STAFF: `${FEATURE}/admin/staff`,
  UPDATE_STAFF:  `${FEATURE}/admin/staff/`,
  LIST_CATEGORY: `${FEATURE}/admin/customer-categories`,
  ROLES: `${FEATURE}/admin/roles`,
  UPDATE_ROLE: `${FEATURE}/admin/roles/`,
  PERMISSION_GROUP:`${FEATURE}/admin/roles/permissions/categories`,
  PERMISSION:`${FEATURE}/admin/roles/permissions`,
  CUSTOMER_LIST:`${FEATURE}/admin/customer`,
  ADD_ADDRESS: `${FEATURE}/admin/customer/add-shipping-address/`,
  ADD_ACCOUNT_BANK: `${FEATURE}/admin/customer/add-bank-user/`,
  CUSTOMER_NOTE: `${FEATURE}/admin/customer/get-notes/`,
  ADD_CUSTOMER_NOTE: `${FEATURE}/admin/customer/add-notes/`,
  BANK_INFO: `${FEATURE}/admin/bank-informations`,
  ADD_SALE_RESPONSIBILITY: `${FEATURE}/admin/customer/add-sale-to-customer`,
  REMOVE_ASSIGN: `${FEATURE}/admin/customer/unassign-customer-sale/`,
  DELETE_ACCOUNT: `${FEATURE}/admin/users/`,
  LOCK_ACCOUNT: `${FEATURE}/admin/users/deactivate/`,
  UNLOCK_ACCOUNT: `${FEATURE}/admin/users/activate/`,
  RESET_PASSWORD: `${FEATURE}/admin/users/reset-password/`,
  ADD_DEFAULT_ADDRESS: `${FEATURE}/admin/customer/set-default/`,
  ADD_DEFAULT_BANK: `${FEATURE}/admin/customer/set-default-banking/`,
  ROLE_USER: `${PROFILE}/user/role`,
  UPDATE_CATE_FOR_CUSTOMER: `${FEATURE}/admin/customer/add-customer-category/`,
  LIST_TOPUP: `${FEATURE}/admin/topups`,
  LIST_WITHDRAW :`${FEATURE}/admin/withdrawal/requests`,
  ADD_TOPUP_MANUAL:`${FEATURE}/admin/topups/manual`,
  BANK_LIST_DEPOSIT: `${FEATURE}/admin/bank-accounts`,
  CONFIRM_TOPUP: `${FEATURE}/admin/topups/`,
  CONFIRM_WITHDRAW:`${FEATURE}/admin/withdrawal/approve/`,
  CANCEL_WITHDRAW: `${FEATURE}/admin/withdrawal/reject/`,
  HISTORY_WITHDRAW: `${FEATURE}/admin/withdrawal/requests/`,
  HISTORY_TOPUP: `${FEATURE}/admin/topups/`,
  GEN_CODE_TOPUP: `${FEATURE}/admin/topups/create-transaction-code`,
  MINUS_TOPUP_MANUAL:`${FEATURE}/admin/topups/manual/deduct`,
  COMPLETE_WITHDRAW: `${FEATURE}/admin/withdrawal/complete/`,
  BANK_LIST_PERMISSION:`${FEATURE}/admin/bank-accounts/`,
  ADD_USER_MANAGE_ACCOUNT_BANK:`${FEATURE}/admin/bank-accounts/`,
  WITHDRAW_DETAIL:`${FEATURE}/admin/withdrawal/requests/detail/`,
  WITHDRAW_HISTORY:`${FEATURE}/admin/withdrawal/`,
  TOPUP_DETAIL:`${FEATURE}/admin/topups/`,

} as const;