const AUTH_PREFIX = "users/v1/auth";
const ONBOARD = "users/v1/onboard";
const PROFILE = "users/v1/profile";
const MEDIA = "medias/v1/files";
const FEATURE = "features/v1";
export const VIEW_IMAGE = "medias/v1/files/view/thumb/";
export const API_TYPE_CONST = {
  LOGIN: `${AUTH_PREFIX}/login`,
  LOGOUT: `${AUTH_PREFIX}/logout`,
  GENERATE_ACCESS_TOKEN: `${AUTH_PREFIX}/generate/access-token`,
  FORGOT_PASSWORD: `${ONBOARD}/forgot-password`,
  VERIFY_OTP: `${ONBOARD}/verify-otp`,
  RESEND_VERIFY_OTP: `${ONBOARD}/resend-verify-otp`,
  CREATE_NEW_PASSWORD: `${ONBOARD}/create-new-password`,
  CREATE_CUSTOMER: `${ONBOARD}/create-customer`,
  GET_PROFILE: `${PROFILE}/me`,
  UPDATE_AVARTAR: `/users/v1/profile/me/avatar`,
  CHANGE_PASSWORD: `/users/v1/users/change-password`,
  UPLOAD_IMAGE: `${MEDIA}/upload`,
  LIST_SALE: `${FEATURE}/admin/sales`,
  CREATE_SALE: `${FEATURE}/admin/sales/add-sales`,
  LIST_STAFF: `${FEATURE}/admin/staff`,
  ADD_STAFF: `${FEATURE}/admin/staff`,
  UPDATE_STAFF: `${FEATURE}/admin/staff/`,
  LIST_CATEGORY: `${FEATURE}/admin/customer-groups`,
  ROLES: `${FEATURE}/admin/roles`,
  UPDATE_ROLE: `${FEATURE}/admin/roles/`,
  PERMISSION_GROUP: `${FEATURE}/admin/roles/permissions/categories`,
  PERMISSION: `${FEATURE}/admin/roles/permissions`,
  CUSTOMER_LIST: `${FEATURE}/admin/customer`,
  CUSTOMER_LIST_ADMIN_SALE: `${FEATURE}/admin/orders/get-all-customer`,
  ADD_ADDRESS: `${FEATURE}/admin/customer/add-shipping-address/`,
  ADD_ACCOUNT_BANK: `${FEATURE}/admin/customer/add-bank-user/`,
  CUSTOMER_NOTE: `${FEATURE}/admin/customer/get-notes/`,
  ADD_CUSTOMER_NOTE: `${FEATURE}/admin/customer/add-notes/`,
  BANK_INFO: `${FEATURE}/admin/bank-informations`,
  ADD_SALE_RESPONSIBILITY: `${FEATURE}/admin/customer/add-sale-to-customer`,
  REMOVE_ASSIGN: `${FEATURE}/admin/customer/unassign-customer-sale/`,
  DELETE_ACCOUNT: `${FEATURE}/admin/users/`,
  LOCK_ACCOUNT: `${FEATURE}/admin/users/deactivate/`,
  UNLOCK_ACCOUNT: `${FEATURE}/admin/users/activate/`,
  RESET_PASSWORD: `${FEATURE}/admin/users/reset-password/`,
  ADD_DEFAULT_ADDRESS: `${FEATURE}/admin/customer/set-default/`,
  ADD_DEFAULT_BANK: `${FEATURE}/admin/customer/set-default-banking/`,
  ROLE_USER: `${PROFILE}/user/role`,
  UPDATE_CATE_FOR_CUSTOMER: `${FEATURE}/admin/customer/add-customer-groups/`,
  LIST_TOPUP: `${FEATURE}/admin/topups`,
  LIST_WITHDRAW: `${FEATURE}/admin/withdrawal/requests`,
  ADD_TOPUP_MANUAL: `${FEATURE}/admin/topups/manual`,
  BANK_LIST_DEPOSIT: `${FEATURE}/admin/bank-accounts`,
  CONFIRM_TOPUP: `${FEATURE}/admin/topups/`,
  CONFIRM_WITHDRAW: `${FEATURE}/admin/withdrawal/approve/`,
  CANCEL_WITHDRAW: `${FEATURE}/admin/withdrawal/reject/`,
  HISTORY_WITHDRAW: `${FEATURE}/admin/withdrawal/requests/`,
  HISTORY_TOPUP: `${FEATURE}/admin/topups/`,
  GEN_CODE_TOPUP: `${FEATURE}/admin/topups/create-transaction-code`,
  MINUS_TOPUP_MANUAL: `${FEATURE}/admin/topups/manual/deduct`,
  COMPLETE_WITHDRAW: `${FEATURE}/admin/withdrawal/complete/`,
  BANK_LIST_PERMISSION: `${FEATURE}/admin/bank-accounts/`,
  ADD_USER_MANAGE_ACCOUNT_BANK: `${FEATURE}/admin/bank-accounts/`,
  WITHDRAW_DETAIL: `${FEATURE}/admin/withdrawal/requests/detail/`,
  WITHDRAW_HISTORY: `${FEATURE}/admin/withdrawal/`,
  TOPUP_DETAIL: `${FEATURE}/admin/topups/`,
  WEBSITE_MANAGE: `${FEATURE}/admin/source-website`,
  UPDATE_SELECTOR_CONFIG: `${FEATURE}/admin/source-website`, // + /{id}/selector-config
  TEST_SELECTOR_CONFIG: `${FEATURE}/admin/source-website/test-selector-config`,
  // Website Account Management
  WEBSITE_ACCOUNT: `${FEATURE}/admin/website-account`,
  // User - Website Accounts assignment
  USER_WEBSITE_ACCOUNTS: `${FEATURE}/admin/users/website-accounts`,
  LIST_REGION: `${FEATURE}/admin/regions`,
  LIST_ORDER: `${FEATURE}/admin/orders`,
  DETAIL_ORDER: `${FEATURE}/orders`,
  LIST_EXCHANGE_RATE: `${FEATURE}/exchange-rate/admin/setting`,
  UPDATE_EXCHANGE_RATE: `${FEATURE}/exchange-rate/admin/setting`,
  GET_DATA_FROM_LINK: `${FEATURE}/products/get-data-from-url`,
  INSURANCE_PACKAGE: `${FEATURE}/insurance-package`,
  FEE_SETTING: `${FEATURE}/fee-setting`,
  SHIPPING_METHOD: `${FEATURE}/shipping-method/setting`,
  BANK_PARTNER: `${FEATURE}/admin/bank-accounts/topup`,
  SURCHANGE_SETTING: `${FEATURE}/product/fee`,
  // Material Transactions (FIFO System)
  MATERIAL_TRANSACTIONS: `${FEATURE}/material-transactions`,
  MATERIAL_TRANSACTIONS_SUMARY: `${FEATURE}/material-transactions/currency-total`,
  MATERIAL_TRANSACTIONS_FIFO_BALANCE: `${FEATURE}/material-transactions/fifo-balance`,
  MATERIAL_TRANSACTIONS_RECALCULATE_FIFO: `${FEATURE}/material-transactions/recalculate-fifo`,

  // FIFO Profit/Loss Reports
  FIFO_PROFIT_LOSS_SUMMARY: `${FEATURE}/fifo/profit-loss/summary`,
  FIFO_PROFIT_LOSS_BY_DATE: `${FEATURE}/fifo/profit-loss/by-date`,
  FIFO_PROFIT_LOSS_ORDERS: `${FEATURE}/fifo/profit-loss/orders`,
  PRODUCT_CATEGORIES: `${FEATURE}/admin/product-categories`,
  PRODUCT_FEE: `${FEATURE}/product/fee`,
  FEE_GET: `${FEATURE}/fee`,
  FEE_GET_ADMIN: `${FEATURE}/fee/get-data-admin`,
  EXCHANGE_RATE: `${FEATURE}/exchange-rate/admin/setting/get-data`,
  CALCULATE_FEE: `${FEATURE}/fee/calculate-fee`,
  CREATE_ORDER: `${FEATURE}/admin/orders`,
  SHIP_ROUTE: `${FEATURE}/shipping-route`,
  GET_TRACKING_ORDER: `${FEATURE}/admin/orders/get-tracking-ship`,
  COMPLETE_SHIPPING: `${FEATURE}/admin/orders/complete-shipping`,
  DASHBOARD_STATS: `${FEATURE}/admin/dashboard/stats`,
  GET_INFO_WEIGHT: `${FEATURE}/product/fee/get-dosmestic-info`,
  CREATE_PRIVATE_NOTE: `${FEATURE}/admin/orders/admin-note`,
  CREATE_PRIVATE_NOTE_CLIENT: `${FEATURE}/orders/order-note`,
  GENERAL_POLICY: `${FEATURE}/admin/general-policy`,
  GEN_PACKAGE_CODE: `${FEATURE}/admin/tracking/gen-package-code`,
  CREATE_TRACKING_ORDER: `${FEATURE}/admin/tracking/order`,
  UPDATE_COD_EACH_ROW: `${FEATURE}/admin/orders/update-cod`,
  GET_DATA_CHECK: `${FEATURE}/fee/get-data`,
  GET_DATA_LIST: `${FEATURE}/exchange-rate/admin/setting/get-data-list`,
  UPDATE_KUPON: `${FEATURE}/admin/orders/update-kupon`,

  // Check Coming
  CHECK_COMING_CREATE: `${FEATURE}/check-coming`,
  CHECK_COMING_LIST: `${FEATURE}/check-coming`,
  CHECK_COMING_GET: `${FEATURE}/check-coming`,
  CHECK_COMING_DELETE: `${FEATURE}/check-coming`,
  CHECK_COMING_SEARCH: `${FEATURE}/check-coming/search`,
  CHECK_COMING_DELETED: `${FEATURE}/check-coming/deleted`,
  CHECK_COMING_PRINTED: `${FEATURE}/check-coming/printed`,

  // Order Management - VN Warehouse
  SCAN_TRACKING_CODE: `${FEATURE}/admin/tracking/scan-tracking`,
  ORDER_ARRIVED_VN_WAREHOUSE: `${FEATURE}/admin/orders/arrived-vn-warehouse`,
  COMPLETE_ORDER_ARRIVED_VN: `${FEATURE}/admin/orders/arrived-vn-warehouse`,
  ORDER_SOURCE_ACCOUNT: `${FEATURE}/admin/orders/source-account`,
  GET_WEBSITE_ACCOUNTS: `${FEATURE}/admin/website-account`,

  TRACKING_PACKAGED: `${FEATURE}/admin/orders/packing`,
  MANAGE_DEBTS: `${FEATURE}/admin/debts`,
  PARTNER_LIST: `${FEATURE}/admin/users/get-all-partner`,
  CREATE_QR_DEBT: `${FEATURE}/admin/debts/create-debt`,
  CREATE_DEBT: `${FEATURE}/admin/debts/create-debt-transaction`,
  LIST_TRANSTACTION_DEBTS: `${FEATURE}/admin/debts/get-list-transaction-debts/`,
  APPROVE_DEBT: `${FEATURE}/admin/debts/approve`,
  CANCEL_DEBTS:`${FEATURE}/admin/debts/canceled`,
  EXPORT_DATA_DEBT: `${FEATURE}/admin/debts/export-excel`,
  DOWNLOAD_EXAMPLE_DEBT: `${FEATURE}/admin/debts/export-template`,
  IMPORT_FILE_DEBT:`${FEATURE}/admin/debts/import-excel`,
  VIP_PACKAGES: `${FEATURE}/admin/vip/packages`,
  TELESALES_LIST:`${FEATURE}/admin/telesales/search`,
  TELESALES_IMPORT:`${FEATURE}/admin/telesales/import`,
  TELESALES_DOWNLOAD_EXAMPLE:`${FEATURE}/admin/telesales/template`,
  TELESSALE_ADD_NOTE: `${FEATURE}/admin/telesales/notes`,
  TELESSALE_ADD_TAG:`${FEATURE}/admin/telesales/add-tags`,
  TELESSALE_UPDATE_TAG:`${FEATURE}/admin/telesales/update-tags/`,
  TELESSALE_DELETE_TAG:`${FEATURE}/admin/telesales/delete-tags/`,
  TELESSALE_DELETE:`${FEATURE}/admin/telesales/delete-tags/`,
  TELESSALE_ASSIGN :`${FEATURE}/admin/telesales/assign-prospect-telesale`,
  TELESSALE_ASSIGN_TAG:`${FEATURE}/admin/telesales/contacts/{contact_id}/tags`,
  TELESSALE_CHANGE_STATUS:`${FEATURE}/admin/telesales/contacts/{contact_id}/status`,
  TELESALE_ACCOUNT:`${FEATURE}/admin/telesales/accounts`,
  TAG_LIST:`${FEATURE}/admin/telesales/tags`,
  DASHBOARD_TELESALE: `${FEATURE}/admin/telesales/dashboard`,
  MANUAL_PARTNER:`${FEATURE}/admin/topups/debt`,
  GET_ALL_PARTNER:`${FEATURE}/admin/users/get-all-partner`,
  CANCEL_ORDER:`${FEATURE}/admin/orders/cancel`,
  TELESALE_TAG_FILTER:`${FEATURE}/admin/telesales/tags-dropdown`,
  TELESALE_ADD_CUSTOMER:`${FEATURE}/admin/telesales/add`,
  TELESALE_UNASSIGN:`${FEATURE}/admin/telesales/contacts/{contact_id}/unassign`,
  TELESALE_CONTACT_UPDATE:`${FEATURE}/admin/telesales/contacts/{id}`,
  SETTING_TELEGRAM:`${FEATURE}/admin/web-setting`,

  // Analytics API
  ANALYTICS_CUSTOMERS_TOP_DEBT: `${FEATURE}/admin/analytics/customers/top-debt`,
  ANALYTICS_CUSTOMERS_TOP_ORDERS: `${FEATURE}/admin/analytics/customers/top-orders`,
  ANALYTICS_CUSTOMERS_TOP_SPENDING: `${FEATURE}/admin/analytics/customers/top-spending`,
  ANALYTICS_CUSTOMERS_NEW: `${FEATURE}/admin/analytics/customers/new`,
  ANALYTICS_CUSTOMERS_INCOMPLETE_ORDERS: `${FEATURE}/admin/analytics/customers/incomplete-orders`,
  ANALYTICS_PRODUCTS_TOP_ORDERED: `${FEATURE}/admin/analytics/products/top-ordered`,
  ANALYTICS_SALES_PERFORMANCE: `${FEATURE}/admin/analytics/sales/performance`,
  ANALYTICS_ORDERS_TIMELINE: `${FEATURE}/admin/analytics/orders/timeline`,
  ANALYTICS_ORDERS_PENDING: `${FEATURE}/admin/analytics/orders/pending`,
  ANALYTICS_MATERIALS_PROFIT_LOSS: `${FEATURE}/admin/analytics/materials/profit-loss`,
  ANALYTICS_SUMMARY: `${FEATURE}/admin/analytics/summary`,
  ORDER_HISTORY:`${FEATURE}/order-history/`,
  AUTION_LINKS:`${FEATURE}/admin/auction/link-auctions`,
  AUTION_CUSTOMERS:`${FEATURE}/admin/auction/auction-customers`,
  AUTION_APPROVE:`${FEATURE}/admin/auction/{id}/approve`,
  AUTION_REJECT:`${FEATURE}/admin/auction/{auctionId}/reject-pending`,
  AUTION_FINAL:`${FEATURE}/admin/auction/{id}/finalize`,
  AUTION_CANCEL:`${FEATURE}/admin/auction/{id}/admin-cancel`,
  AUTION_EXCUTE_PENDING:`${FEATURE}/admin/auction/{auctionId}/execute-pending`
} as const;
