export const KEY_STORAGE = {
  TOKEN: 'token',
  INFO_APPLICATION: 'infoApplication',
  USER_INFO: 'userInfo',
  EMAIL_CHANGE_PASSWORD: 'emailChangePassword',
  REFRESH_TOKEN: 'refreshToken',
  HOME_SEARCH: 'homeSearch',
  BANNED_WORD: 'bannedWord',
  PROFILE_INFO: 'profileInfo',
  TIME_VISIT_MY_PAGE: 'timeVisitMyPage',
  CALL_INFO: 'callInfo',
  CALL_SETING: 'callSetting',
  OPENTOK_CALL_DATA: 'opentokCallData',
  NOTIFICATION_TOKEN: 'notificationToken',
  CM_CODE: 'cmCode',
  TOKEN_REGISTER: '_token_register',
  SEARCH_INFO: '_search_info',
  EMAIL: '_email',
  HIDE_NEWS: 'hide_news',
  USER_CLOSE_NEWS: 'user_close_news',
  USER_SECURITY: '_info',
  DISPLAY_LIST_GRID_USER: '_display_list_grid_user',
  DISPLAY_DIALOG_SEARCH_USER: '_display_dialog_search_user_',
  NAME_SEARCH: '_name_search_',
  CHAT_MENU_BUTTON: 'chat_menu_button',
  GENDER: 'gender',
  BIRTHDAY: 'birthday',
  TUTORIAL: 'tutorial',
  REGISTER_TIME: 'register_time',
  TUTORIAL_HOME: 'tutorial_home',
  TUTORIAL_SETTING: 'tutorial_setting',
  MANAGER_POPUP_IN_HOME: 'manager_popup_in_home',
  IS_FIRST_TIME_CALL_SETTING: 'is_first_time_call_setting',
};

export const KEEP_KEYS_STORAGE = [KEY_STORAGE.MANAGER_POPUP_IN_HOME];
