import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import AppProvider from "@/app/app-provider";
import "./globals.css";
import I18nProvider from "@/components/I18nProvider";
import AntdRegistry from "@/components/AntdRegistry";
import Script from "next/script";
import GoogleFontsLoader from "@/components/GoogleFontsLoader";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  weight: ["100", "200", "300", "400", "500", "600", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CRM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"
        />
      </head>
      <body className={`${notoSansJP.variable}`}>
        <GoogleFontsLoader />
        <Script
          id="cache-manager-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
(function() {
  'use strict';

  // Early error patterns that should trigger cache clear
  const CRITICAL_ERROR_PATTERNS = [
    'Cannot read properties of null',
    'Cannot read property',
    'ChunkLoadError',
    'Loading chunk',
    'Loading CSS chunk',
    'Unexpected token',
    'Script error'
  ];

  // Check if error should trigger cache clear
  function shouldClearCache(error) {
    const errorMessage = error.message || '';
    const errorStack = error.stack || '';
    return CRITICAL_ERROR_PATTERNS.some(pattern =>
      errorMessage.includes(pattern) || errorStack.includes(pattern)
    );
  }

  // Clear all cookies
  function clearAllCookies() {
    try {
      const cookies = document.cookie.split(';');
      for (let cookie of cookies) {
        const eqPos = cookie.indexOf('=');
        const name = eqPos > -1 ? cookie.substr(0, eqPos).trim() : cookie.trim();
        if (name) {
          document.cookie = name + '=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/';
          const domain = window.location.hostname.split('.').slice(-2).join('.');
          document.cookie = name + '=;expires=Thu, 01 Jan 1970 00:00:00 GMT;path=/;domain=.' + domain;
        }
      }
    } catch (error) {
      console.error('[EarlyCacheManager] Error clearing cookies:', error);
    }
  }

  // Show user-friendly message with dynamic language support
  function showCacheClearMessage() {
    // Try to get i18n instance if available
    let refreshingMessage = 'Đang làm mới ứng dụng để khắc phục...';
    let pleaseWaitMessage = 'Vui lòng đợi trong giây lát...';

    try {
      // Try to access i18n if available
      if (window.i18next && window.i18next.t) {
        refreshingMessage = window.i18next.t('errorHandling.refreshingApp');
        pleaseWaitMessage = window.i18next.t('errorHandling.pleaseWait');
      }
    } catch (e) {
      // Fall back to Vietnamese as default
    }

    const overlay = document.createElement('div');
    overlay.style.cssText =
      'position: fixed;' +
      'top: 0;' +
      'left: 0;' +
      'width: 100%;' +
      'height: 100%;' +
      'background: rgba(0, 0, 0, 0.8);' +
      'color: white;' +
      'display: flex;' +
      'align-items: center;' +
      'justify-content: center;' +
      'font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;' +
      'font-size: 16px;' +
      'z-index: 9999;' +
      'text-align: center;' +
      'padding: 20px;';

    overlay.innerHTML =
      '<div style="background: white; color: #333; padding: 30px; border-radius: 10px; max-width: 400px;">' +
      '<div style="margin-bottom: 20px;">⚠️</div>' +
      '<div style="margin-bottom: 20px;">' + refreshingMessage + '</div>' +
      '<div style="font-size: 14px; opacity: 0.7;">' + pleaseWaitMessage + '</div>' +
      '</div>';

    document.body.appendChild(overlay);
    return overlay;
  }

  // Clear all and reload
  function clearAllAndReload(reason) {
    console.warn('[EarlyCacheManager] Clearing cache:', reason);
    try {
      if (typeof localStorage !== 'undefined') {
        localStorage.clear();
      }
      if (typeof sessionStorage !== 'undefined') {
        sessionStorage.clear();
      }
      clearAllCookies();
      if (window.location) {
        window.location.reload(true);
      }
    } catch (error) {
      console.error('[EarlyCacheManager] Error during cache clearing:', error);
      if (window.location) {
        window.location.reload();
      }
    }
  }

  // Early error handler
  window.addEventListener('error', function(event) {
    const error = event.error;
    if (error && shouldClearCache(error)) {
      console.error('[EarlyGlobal] Critical error detected:', error);
      showCacheClearMessage();
      setTimeout(function() {
        clearAllAndReload('Early global error handler triggered');
      }, 2000);
    }
  });

  // Early unhandled promise rejection handler
  window.addEventListener('unhandledrejection', function(event) {
    const error = event.reason;
    if (error instanceof Error && shouldClearCache(error)) {
      console.error('[EarlyGlobal] Critical promise rejection:', error);
      showCacheClearMessage();
      setTimeout(function() {
        clearAllAndReload('Early unhandled promise rejection');
      }, 2000);
    }
  });

  console.log('[EarlyCacheManager] Initialized');
})();
            `
          }}
        />
        <I18nProvider>
          <AppProvider><AntdRegistry>{children}</AntdRegistry></AppProvider>
        </I18nProvider>
      </body>
    </html>
  );
}
